name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
        
    - name: Install golangci-lint
      run: make tools
      
    - name: Run make lint
      run: make lint
      
    - name: Run make test
      run: make test
      
    - name: Run make build
      run: make build
      
    - name: Upload coverage reports
      uses: actions/upload-artifact@v4
      with:
        name: coverage-reports
        path: |
          build/coverage.out
          build/coverage.html
